name: VCNotebook
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    iOS: 15.0
  developmentLanguage: en
  xcodeVersion: 15.0

settings:
  SWIFT_VERSION: 5.9
  MARKETING_VERSION: 1.0
  CURRENT_PROJECT_VERSION: 1

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: 10.0.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    majorVersion: 7.0.0
  Supabase:
    url: https://github.com/supabase/supabase-swift
    majorVersion: 2.0.0

targets:
  VCNotebook:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources:
      - VCNotebook
    settings:
      INFOPLIST_FILE: VCNotebook/Resources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.yourname.VCNotebook
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCore
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: Supabase
        product: Supabase
    preBuildScripts:
      - script: |
          echo "Building VCNotebook..."
        name: Pre-Build
        showEnvVars: false

schemes:
  VCNotebook:
    build:
      targets:
        VCNotebook: all
    run:
      config: Debug
    archive:
      config: Release

